### ISSUE TITLE
DatabaseError with new project in django-cms 2.3rc2 and Django-1.4

### ISSUE THREAD

**Issue by mrsarm** [MegaMark16/django-cms-themes#7]
I'm cannot create the tables of django-cms, when I active 'cms_themes' in INSTALLED_APPS, and run 'python manage.py migrate' to create in Postgres the tables, this is launched:

```
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/South-0.7.5-py2.7.egg/south/management/commands/migrate.py", line 107, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/South-0.7.5-py2.7.egg/south/migration/__init__.py", line 199, in migrate_app
    applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
  File "/usr/local/lib/python2.7/dist-packages/South-0.7.5-py2.7.egg/south/migration/__init__.py", line 72, in check_migration_histories
    for h in histories:
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/models/query.py", line 875, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4-py2.7.egg/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: transacción abortada, las órdenes serán ignoradas hasta el fin de bloque de transacción
```

You can see my code in https://github.com/mrsarm/cmsproject

**Comment by MegaMark16** [comment]
Hey @mrsarm, thanks for bringing this to my attention.  I'm trying to recreate the issue but I'm running into issues with versions I think.  Could you send me the output of your "pip freeze" command so I can try to get all my library versions to match yours?  Thanks!

**Comment by mrsarm** [comment]
```
Babel==0.9.6
Brlapi==0.5.5
BzrTools==2.4.0
CherryPy==3.1.2
Django==1.4
FormEncode==1.2.2
GnuPGInterface==0.3.2
Mako==0.3.6
MarkupSafe==0.9.2
PAM==0.4.2
PIL==1.1.7
PyChart==1.39
PyYAML==3.09
Pygments==1.4
Pyro==3.9.1
South==0.7.5
TurboCheetah==1.0
TurboGears==1.0.8
TurboJson==1.1.4
TurboKid==1.0.5
Twisted-Core==10.2.0
Twisted-Names==10.1.0
Twisted-Web==10.2.0
Werkzeug==0.6.2
adium-theme-ubuntu==0.3.1
apt-xapian-index==0.41
apturl==0.5ubuntu1
bpython==0.9.7.1
bzr==2.4.1
bzr-dbus==0.1-
bzr-gtk==0.100.0
bzr-xmloutput==0.8.7.dev
chardet==2.0.1
cmsplugin-filer==0.8.0
command-not-found==0.1
configglue==1.0
configobj==4.7.2
decorator==3.2.0
defer==1.0.2
distribute==0.6.24
django-classy-tags==0.3.4.1
django-cms==2.3.post0
django-cms-themes==1.0.10
django-evolution==0.6.7
django-filebrowser==3.0
django-filer==0.9a1
django-grappelli==2.4.0
django-haystack==1.2.7
django-inplaceedit==0.81
django-localeurl==1.5
django-maintenancemode==0.10
django-mptt==0.5.2
django-pagination==1.0.7
django-piston==0.2.2
django-polymorphic==0.2
django-sekizai==0.6.1
django-tinymce==1.5.1b2
django-transmeta==0.6.7
dulwich==0.7.0
duplicity==0.6.15
easy-thumbnails==1.0.3
explorer==1.1.2
fastimport==0.9.0dev0
feedparser==4.1
foolscap==0.6.1
gnome-app-install==0.4.7-nmu1ubuntu2
html5lib==0.95
httplib2==0.7.2
ipython==0.10.1
jockey==0.9.4
kerberos==1.0
keyring==0.5.1
launchpadlib==1.9.7
lazr.restfulclient==0.11.1
lazr.uri==1.0.2
louis==2.3.0
lxml==2.3
mediawiki==0.0.1
nvidia-common==0.0.0
oauth==1.0a
onboard==0.95.1
oneconf==0.2.6.7
ooop==0.2.3
papyon==0.5.5
paramiko==1.7.7.1
pexpect==2.3
piston-mini-client==0.6
protobuf==2.4.0a
psycopg2==2.2.1
pyOpenSSL==0.10
pycrypto==2.1.0
pycups==1.9.54
pycurl==7.19.0
pydot==1.0.2
pygpgme==0.1
pyinotify==0.9.1
pyparsing==1.5.2
pyserial==2.5
pysmbc==1.0.10
python-apt==0.8.0ubuntu9
python-dateutil==1.4.1
python-debian==0.1.20ubuntu2
python-magic==0.4.1
python-openid==2.2.4
python-virtkey==0.60.0
pytz==2010b
pyudev==0.8
pyxdg==0.19
qbzr==0.20.0
rabbitvcs==0.14.2.1
recaptcha-client==1.0.5
reportlab==2.5
sessioninstaller==0.0.0
simplejson==2.1.2
synaptiks==0.5.3
system-service==0.1.6
uTidylib==0.2
ubuntu-sso-client==1.4.0
ubuntuone-couch==0.3.0
ubuntuone-installer==2.0.0
ubuntuone-storage-protocol==2.0.0
ufw==0.30.1-1ubuntu1
unattended-upgrades==0.1
usb-creator==0.2.23
vboxapi==1.0
vobject==0.8.1c
wadllib==1.1.8
wsgi-intercept==0.4
wsgiref==0.1.2
wxPython==2.8.11.0
wxPython-common==2.8.11.0
xdiagnose==1.1
xkit==0.0.0
xlwt==0.7.2
zope.interface==3.6.1
```
